package view.feedbackPanels.updatePanel;

import controllers.CounselorController;
import controllers.FeedbackController;

import java.util.ArrayList;
import javax.swing.*;
import java.awt.Window;

        
public class UpdatePanel extends javax.swing.JPanel {

    public UpdatePanel(String studentName, String counselorName, int rating, String comment, String id) {
        initComponents();

        // Group the rating radio buttons
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        buttonGroup1.add(jRadioButton5);
        
        // Display Feedback id in label
        idLabel.setText(id);
        
        // Items to display in combo box
        populateCounselorComboBox();             
        
        // Set student name text field
        txtStudentName.setText(studentName);

        // Set counselor combo box selection
        cbCounselor.setSelectedItem(counselorName);

        // Select the rating radio button according to rating value (assuming rating is 1-5)
        switch (rating) {
            case 1: jRadioButton1.setSelected(true); break;
            case 2: jRadioButton2.setSelected(true); break;
            case 3: jRadioButton3.setSelected(true); break;
            case 4: jRadioButton4.setSelected(true); break;
            case 5: jRadioButton5.setSelected(true); break;
            default: 
                // Optionally, deselect all or set a default
                buttonGroup1.clearSelection();
        }

        // Set comment text area
        txtComment.setText(comment);
    }

    private void populateCounselorComboBox() {
        cbCounselor.removeAllItems(); // Clear existing items if any

        ArrayList<String> counselorNames = CounselorController.getAllCounselorNames();
        for (String name : counselorNames) {
            cbCounselor.addItem(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblCounselor = new javax.swing.JLabel();
        cbCounselor = new javax.swing.JComboBox<>();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        lblDate1 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        fSubmit = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 242, 255));

        lblCounselor.setText("Counselor:");

        cbCounselor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCounselor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCounselorActionPerformed(evt);
            }
        });

        lblStudentName.setText("Student:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblDate.setText("Rating:");

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        jRadioButton1.setText("1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("2");

        lblDate1.setText("Comment:");

        jRadioButton3.setText("3");

        fSubmit.setText("Submit");
        fSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSubmitActionPerformed(evt);
            }
        });

        jRadioButton4.setText("4");

        jRadioButton5.setText("5");

        jLabel1.setText("Feedback:");

        idLabel.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton5))
                        .addComponent(lblDate)
                        .addComponent(lblStudentName)
                        .addComponent(lblCounselor)
                        .addComponent(lblDate1)
                        .addComponent(cbCounselor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStudentName)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCounselor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCounselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(3, 3, 3)
                .addComponent(lblDate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fSubmit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCounselorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCounselorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCounselorActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void fSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSubmitActionPerformed
        String iD = idLabel.getText();
        String studentName = txtStudentName.getText();
        String counselorName = (String) cbCounselor.getSelectedItem();  // assuming JComboBox
        int rating = getSelectedRating();  // implement a method to get selected radio button value
        String comment = txtComment.getText();

        String result = FeedbackController.updateFeedback(Integer.parseInt(iD), studentName, counselorName, rating, comment);

        if ("SUCCESS".equals(result)) {
            JOptionPane.showMessageDialog(this, "Feedback updated successfully!");
            Window window = SwingUtilities.getWindowAncestor(this);
            if (window != null) {
                window.dispose();  // close the window
            }
        } else {
            JOptionPane.showMessageDialog(this, "Update failed: " + result);
        }
    }//GEN-LAST:event_fSubmitActionPerformed

// Helper method to get selected rating from radio buttons
private int getSelectedRating() {
    if (jRadioButton1.isSelected()) return 1;
    if (jRadioButton2.isSelected()) return 2;
    if (jRadioButton3.isSelected()) return 3;
    if (jRadioButton4.isSelected()) return 4;
    if (jRadioButton5.isSelected()) return 5;
    return 0; // or handle no selection case
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCounselor;
    private javax.swing.JButton fSubmit;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCounselor;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
