
package view;

import view.feedbackPanels.AddFeedbackPanel;
import view.feedbackPanels.ViewFeedbackPanel;
import view.feedbackPanels.UpdateFeedbackPanel;
import view.feedbackPanels.DeleteFeedbackPanel;

public class FeedbackPanel extends javax.swing.JPanel {

    /**
     * Creates new form FeedbackPanel
     */
    public FeedbackPanel() {
        initComponents();
        fPanel.setLayout(new java.awt.BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fPanel = new javax.swing.JPanel();
        faddButton = new javax.swing.JButton();
        fviewButton = new javax.swing.JButton();
        fupdateButton = new javax.swing.JButton();
        fdeleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("Book Appointment");

        jButton2.setText("View Appointments");

        jButton3.setText("Update Appointment");

        jButton4.setText("Cancel Appointment");

        jLabel1.setText("Manage Appointments ");

        jButton5.setText("Book Appointment");

        jButton6.setText("View Appointments");

        jButton7.setText("Update Appointment");

        jButton8.setText("Cancel Appointment");

        jLabel2.setText("Manage Appointments ");

        javax.swing.GroupLayout fPanelLayout = new javax.swing.GroupLayout(fPanel);
        fPanel.setLayout(fPanelLayout);
        fPanelLayout.setHorizontalGroup(
            fPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        fPanelLayout.setVerticalGroup(
            fPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        faddButton.setText("Add Feedback");
        faddButton.setMaximumSize(new java.awt.Dimension(108, 23));
        faddButton.setMinimumSize(new java.awt.Dimension(108, 23));
        faddButton.setPreferredSize(new java.awt.Dimension(108, 23));
        faddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faddButtonActionPerformed(evt);
            }
        });

        fviewButton.setText("View Feedback");
        fviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fviewButtonActionPerformed(evt);
            }
        });

        fupdateButton.setText("Update Feedback");
        fupdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fupdateButtonActionPerformed(evt);
            }
        });

        fdeleteButton.setText("Delete Feedback");
        fdeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdeleteButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Manage Feedback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(faddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fviewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fupdateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fdeleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(faddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fviewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fupdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fdeleteButton)
                        .addGap(0, 288, Short.MAX_VALUE))
                    .addComponent(fPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void faddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faddButtonActionPerformed
        fPanel.removeAll();
        fPanel.add(new AddFeedbackPanel(), java.awt.BorderLayout.CENTER);
        fPanel.revalidate();
        fPanel.repaint();
    }//GEN-LAST:event_faddButtonActionPerformed

    private void fviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fviewButtonActionPerformed
        fPanel.removeAll();
        fPanel.add(new ViewFeedbackPanel(), java.awt.BorderLayout.CENTER);
        fPanel.revalidate();
        fPanel.repaint();
    }//GEN-LAST:event_fviewButtonActionPerformed

    private void fdeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdeleteButtonActionPerformed
        fPanel.removeAll();
        fPanel.add(new DeleteFeedbackPanel(), java.awt.BorderLayout.CENTER);
        fPanel.revalidate();
        fPanel.repaint();
    }//GEN-LAST:event_fdeleteButtonActionPerformed

    private void fupdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fupdateButtonActionPerformed
        // TODO add your handling code here:
        fPanel.removeAll();
        fPanel.add(new UpdateFeedbackPanel(), java.awt.BorderLayout.CENTER);
        fPanel.revalidate();
        fPanel.repaint();
    }//GEN-LAST:event_fupdateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JPanel fPanel;
    private javax.swing.JButton faddButton;
    private javax.swing.JButton fdeleteButton;
    private javax.swing.JButton fupdateButton;
    private javax.swing.JButton fviewButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
