/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.appointmentsPanels;

import dao.AppointmentDAO;
import dao.CounselorDAO;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Appointment;
import model.Counselor;
import utils.TimeUtils;

/**
 *
 * @author reina
 */
public class BookAppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookAppointmentPanel
     */
    public BookAppointmentPanel() {
        initComponents();
        cbTime.removeAllItems(); 
        for (int hour = 8; hour <= 16; hour++) {
            String formattedTime = String.format("%02d:00", hour);
            cbTime.addItem(formattedTime);
        }
        populateCounselorComboBox();
    }
    private void populateCounselorComboBox() {
        CounselorDAO dao = new CounselorDAO();
        ArrayList<String> counselorNames = dao.getAllCounselorNames();

        cbCounselor.removeAllItems(); // Clear existing items if any
        for (String name : counselorNames) {
            cbCounselor.addItem(name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        cbTime = new javax.swing.JComboBox<>();
        lblCounselor = new javax.swing.JLabel();
        cbCounselor = new javax.swing.JComboBox<>();
        dcDate = new com.toedter.calendar.JDateChooser();
        submit = new javax.swing.JButton();

        lblStudentName.setText("StudentName:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblDate.setText("Date:");

        lblTime.setText("Time (mm:hh)");

        cbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCounselor.setText("Counselor:");

        cbCounselor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submit.setText("Make Appointment");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate)
                    .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(lblCounselor)
                    .addComponent(lblTime)
                    .addComponent(cbCounselor, 0, 189, Short.MAX_VALUE)
                    .addComponent(cbTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCounselor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCounselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String studentName = txtStudentName.getText().trim();
        String counselorName = cbCounselor.getSelectedItem().toString();
        String timeStr = cbTime.getSelectedItem().toString();
        java.util.Date selectedDate = dcDate.getDate();

        // 1. Validate empty fields
        if (studentName.isEmpty() || selectedDate == null || timeStr == null || counselorName == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Convert date and time
        LocalDate date = selectedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalTime time = LocalTime.parse(timeStr);

        // 3. Get counselor ID and full object
        CounselorDAO counselorDAO = new CounselorDAO();
        int counselorId = counselorDAO.getCounselorIdByName(counselorName);
        Counselor counselor = counselorDAO.getCounselorByName(counselorName);

        if (counselorId == -1 || counselor == null) {
            JOptionPane.showMessageDialog(this, "Counselor not found in database.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Check availability
        System.out.println("HERERERER"+counselor.getAvailability());
        if (!TimeUtils.isWithinRange(counselor.getAvailability(), time)) {
            JOptionPane.showMessageDialog(this, "Selected time is outside the counselor's availability.", "Invalid Time", JOptionPane.WARNING_MESSAGE);
            return;
        }
        System.out.println("Availability: " + counselor.getAvailability());
        System.out.println("Selected Time: " + time);

        // 5. Check if counselor is already booked
        AppointmentDAO appointmentDAO = new AppointmentDAO();
        boolean isBooked = appointmentDAO.isCounselorBooked(
            counselorId,
            java.sql.Date.valueOf(date),
            java.sql.Time.valueOf(time)
        );

        if (isBooked) {
            JOptionPane.showMessageDialog(this, "This counselor is already booked at the selected time.", "Conflict", JOptionPane.WARNING_MESSAGE);
            return;
            
    }

    // 6. Success — show a confirmation (insert logic comes next)
        JOptionPane.showMessageDialog(this, "Appointment slot is valid. Proceed to save!", "Success", JOptionPane.INFORMATION_MESSAGE);

   
        Appointment appointment = new Appointment(studentName, counselorId, date, time, "Scheduled");
        appointmentDAO.addAppointment(appointment); 
        populateCounselorComboBox();
    }//GEN-LAST:event_submitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCounselor;
    private javax.swing.JComboBox<String> cbTime;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel lblCounselor;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}