/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.appointmentsPanels;

import controllers.AppointmentsController;
import controllers.CounselorController;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author reina
 */
public class BookAppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookAppointmentPanel
     */
    public BookAppointmentPanel() {
        initComponents();
        cbTime.removeAllItems(); 
        for (int hour = 8; hour <= 16; hour++) {
            String formattedTime = String.format("%02d:00", hour);
            cbTime.addItem(formattedTime);
        }
        populateCounselorComboBox();
    }
    private void populateCounselorComboBox() {
        cbCounselor.removeAllItems(); // Clear existing items if any

        ArrayList<String> counselorNames = CounselorController.getAllCounselorNames();
        for (String name : counselorNames) {
            cbCounselor.addItem(name);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        cbTime = new javax.swing.JComboBox<>();
        lblCounselor = new javax.swing.JLabel();
        cbCounselor = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        dcDate = new com.toedter.calendar.JDateChooser();

        lblStudentName.setText("Student:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        lblDate.setText("Date:");

        lblTime.setText("Time (mm:hh)");

        cbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCounselor.setText("Counselor:");

        cbCounselor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submit.setText("Make Appointment");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDate)
                        .addComponent(lblStudentName)
                        .addComponent(txtStudentName)
                        .addComponent(lblCounselor)
                        .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCounselor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCounselor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCounselor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtStudentNameActionPerformed

    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String studentName = txtStudentName.getText().trim();
        String counselorName = cbCounselor.getSelectedItem() != null ? cbCounselor.getSelectedItem().toString() : null;
        String timeStr = cbTime.getSelectedItem() != null ? cbTime.getSelectedItem().toString() : null;
        java.util.Date selectedDate = dcDate.getDate();

        String result = AppointmentsController.bookAppointment(studentName, counselorName, selectedDate, timeStr);

        if (result.equals("SUCCESS")) {
            JOptionPane.showMessageDialog(this, "Appointment slot is valid. Appointment saved!", "Success", JOptionPane.INFORMATION_MESSAGE);
            populateCounselorComboBox();
        } else {
            JOptionPane.showMessageDialog(this, result, "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_submitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCounselor;
    private javax.swing.JComboBox<String> cbTime;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JLabel lblCounselor;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}